remove autoloads which require evil
Otherwise, user can get

  Error: (void-function evil-define-text-object)

if evil is not already require'd, which sort of takes away the point of
autoloading. Also, errors on startup just due to installation (no
touching of .emacs.d/init.el) can be quite confusing.